import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Police from "../components/Call/17";
import UrgenceEuropéen from "../components/Call/112";
import Bedroom from "../components/Call/115";
import Samu from "../components/Call/15";
import Malentendants from "../components/Call/114";

export default function Home() {
  const returnClick = (e) => {
    window.location.replace("https://google.fr/");
    return false;
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#061B2F"></meta>
      </Head>

      <main className={styles.main}>
        <div className="phlav_grid">
          <div className="div_1">
            <section className={styles.welcome}>
              <h1> {"Helpquit | Côtes-d'Armor"} </h1>
              <h2 className={styles.quote}>
                Signaler des violences conjugales, intrafamiliales, sexistes et
                sexuelles
              </h2>
            </section>
            <section className={styles.sred}>
              <h1>{"Pour obtenir de l'aide en cas d'urgence (France)"}</h1>
            </section>

            <Police />
            <UrgenceEuropéen />
            <Bedroom />
            <Samu />
            <Malentendants />
          </div>

          <div className="div_2"></div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
      <div>
        <button className={styles.return} onClick={returnClick}>
          Sortir d’ici (Sans laisser de traces)
        </button>
      </div>
    </div>
  );
}
